// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZrITNvDgfPIFIm5uNhR7O-2qJPjAVALI',
    appId: '1:201558308644:android:f8934c4b49aeede17425b1',
    messagingSenderId: '201558308644',
    projectId: 'my-demo-c',
    storageBucket: 'my-demo-c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4OH8jr-NmznBcYRiJuXSxxYgzgs9kNhc',
    appId: '1:201558308644:ios:3a8ec237c2282a6f7425b1',
    messagingSenderId: '201558308644',
    projectId: 'my-demo-c',
    storageBucket: 'my-demo-c.appspot.com',
    iosClientId: '201558308644-4soqv2rgp4lsfadmhsicov6j4qioeau0.apps.googleusercontent.com',
    iosBundleId: 'com.chaudharyjatin115.com.testCloudFirebase',
  );
}
